import {views,movements} from './views.js';
import {icon,escape as e,money} from './components.js';
import {vehicleService,transactionService,benefitsService,memberService,settingsService} from './services/index.js';
const main=document.querySelector('#main'),dialog=document.querySelector('#dialog');
const routes={inicio:'Inicio',consumos:'Consumos',beneficios:'Beneficios',membresia:'Membresía',ayuda:'Ayuda'};
let route='inicio',timer;
function render(){route=location.hash.slice(1) in routes?location.hash.slice(1):'inicio';main.innerHTML=views[route]();document.querySelector('#navigation').innerHTML=Object.entries(routes).map(([id,label])=>`<a href="#${id}" ${id===route?'aria-current="page"':''}>${icon(id)}<span>${label}</span></a>`).join('');window.scrollTo(0,0);main.focus({preventScroll:true});}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('visible'),4000);}
function modal(content){dialog.innerHTML=`<button class="close icon-button" data-close aria-label="Cerrar">×</button>${content}`;dialog.showModal();}
document.querySelector('#notifications').innerHTML=icon('bell')+'<i class="notification-dot"></i>';
document.addEventListener('click',event=>{const el=event.target.closest('button');if(!el)return;
if(el.hasAttribute('data-close'))dialog.close();
if(el.dataset.route)location.hash=el.dataset.route;
if(el.hasAttribute('data-recharge'))modal('<span class="eyebrow">TU SIGUIENTE VIAJE</span><h2>Recargar saldo</h2><p>Recarga simulada. No se realizará ningún cobro.</p><form id="recharge-form"><label>Monto en soles<input name="amount" type="number" inputmode="decimal" min="10" max="2000" step="0.01" value="50" required></label><p class="form-error" role="alert"></p><button class="primary">Confirmar recarga</button></form>');
if(el.dataset.tab){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===el)));document.querySelector('#movements').innerHTML=movements(el.dataset.tab);}
if(el.dataset.detail){const t=transactionService.list().find(t=>t.id===el.dataset.detail);modal(`<span class="eyebrow">DETALLE DE MOVIMIENTO</span><h2>${money(t.amount)}</h2><p>${e(t.station)}</p><dl><dt>Fecha</dt><dd>${new Date(t.date).toLocaleString('es-PE')}</dd><dt>Vehículo</dt><dd>${e(t.vehicle)}</dd><dt>Puntos obtenidos</dt><dd>${t.points}</dd><dt>Referencia</dt><dd>${e(t.id)}</dd></dl><p class="fine-print">Operación ficticia · Primax Prime</p>`);}
if(el.dataset.benefit){const b=benefitsService.list().find(b=>b.id===el.dataset.benefit);modal(`<span class="eyebrow">BENEFICIO PRIME</span><h2>${e(b.title)}</h2><p>${e(b.description)}</p><p>Canje por <strong>${b.cost} puntos</strong>. Uso único por código en esta demo.</p><p class="fine-print">Vigencia simulada: 31/12/2026. Sujeto a disponibilidad en estaciones participantes. Sin validez comercial.</p><p class="form-error" role="alert"></p><button class="primary" data-redeem="${b.id}">Canjear por ${b.cost} puntos</button>`);}
if(el.dataset.redeem){try{const coupon=benefitsService.redeem(el.dataset.redeem);dialog.close();render();toast(`Canje listo. Código: ${coupon.id.slice(0,8).toUpperCase()}`);}catch(err){dialog.querySelector('.form-error').textContent=err.message;}}
if(el.id==='notifications')modal(`<h2>Notificaciones</h2><p>${settingsService.get().notifications?'¡Bienvenido a Prime! Descubre tus beneficios y disfruta cada parada.':'Las notificaciones de promociones están desactivadas en tus preferencias.'}</p><p class="fine-print">Mensajes simulados, sin conexión a un servicio push.</p>`);
if(el.hasAttribute('data-assistance'))modal('<h2>Asistencia Prime</h2><p>Este canal es una demostración local. No se enviará información a terceros.</p><form id="support-form"><label>¿En qué podemos ayudarte?<textarea name="message" maxlength="500" required rows="4"></textarea></label><button class="primary">Registrar consulta demo</button></form>');
});
document.addEventListener('change',event=>{if(event.target.id==='vehicle'){vehicleService.select(event.target.value);toast('Vehículo actualizado');}if(event.target.id==='notification-setting'){settingsService.notifications(event.target.checked);toast('Preferencia guardada');}});
document.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);try{if(event.target.id==='recharge-form'){transactionService.recharge(data.get('amount'));dialog.close();render();toast('Recarga simulada completada');}if(event.target.id==='profile-form'){memberService.setName(data.get('name'));render();toast('Datos guardados');}if(event.target.id==='support-form'){dialog.close();toast('Consulta demo registrada. No se ha enviado.');}}catch(err){const error=event.target.querySelector('.form-error');if(error)error.textContent=err.message;else toast(err.message);}});
window.addEventListener('hashchange',render);render();
