import {views,movements} from './views.js';
import {icon,escape as e,money} from './components.js';
import {vehicleService,transactionService,benefitsService,memberService,settingsService,refreshData,resetData} from './services/index.js';
import {authService} from './services/authService.js';
import {loginView} from './login.js';
import {SESSION_KEY} from './services/session.js';
const main=document.querySelector('#main'),dialog=document.querySelector('#dialog');
const routes={inicio:'Inicio',consumos:'Consumos',beneficios:'Beneficios',membresia:'Membresía',ayuda:'Ayuda'};
let route='inicio',timer,ready=false;
async function synchronize(){if(!authService.isAuthenticated())return;try{const changed=await refreshData();if(!authService.isAuthenticated())return;ready=true;if(changed&&!dialog.open&&!document.activeElement?.matches('input,textarea,select')&&['inicio','consumos','beneficios','membresia'].includes(route)){const scroll=scrollY;const tab=document.querySelector('[data-tab][aria-selected="true"]')?.dataset.tab;render();if(tab)document.querySelector('[data-tab="'+tab+'"]')?.click();scrollTo(0,scroll);}}catch(err){toast(err.message);if(!authService.isAuthenticated()){resetData();ready=false;render();}}}
async function boot(){if(authService.isAuthenticated()){main.innerHTML='<section class="panel" role="status">Cargando tu membresía…</section>';try{await refreshData();ready=true;}catch(err){toast(err.message);if(authService.isAuthenticated()){main.innerHTML='<section class="panel"><p>No pudimos cargar tu membresía.</p><button class="primary" data-retry>Cargar nuevamente</button><button data-logout>Cerrar sesión</button></section>';return;}}}goHome();}
function render(){const authenticated=authService.isAuthenticated();document.body.classList.toggle('login-mode',!authenticated);document.querySelector('.header').hidden=!authenticated;document.querySelector('#navigation').hidden=!authenticated;document.querySelector('.demo').hidden=!authenticated;if(authenticated&&!ready)return;if(!authenticated){if(dialog.open)dialog.close();main.innerHTML=loginView();document.querySelector('#navigation').innerHTML='';}else{route=location.hash.slice(1) in routes?location.hash.slice(1):'inicio';main.innerHTML=views[route]();document.querySelector('#navigation').innerHTML=Object.entries(routes).map(([id,label])=>`<a href="#${id}" ${id===route?'aria-current="page"':''}>${icon(id)}<span>${label}</span></a>`).join('');if(route==='membresia')main.insertAdjacentHTML('beforeend','<section class="panel"><h2>Tu sesión</h2><p>Sesión de Primax Prime.</p><button type="button" class="logout-button" data-logout>Cerrar sesión</button></section>');}window.scrollTo(0,0);main.focus({preventScroll:true});}
function goHome(){history.replaceState(null,'',location.pathname+location.search+'#inicio');render();}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('visible'),4000);}
function modal(content){dialog.innerHTML=`<button class="close icon-button" data-close aria-label="Cerrar">×</button>${content}`;dialog.showModal();}
document.querySelector('#notifications').innerHTML=icon('bell')+'<i class="notification-dot"></i>';
document.addEventListener('click',async event=>{const el=event.target.closest('button');if(!el)return;
if(el.hasAttribute('data-toggle-password')){const input=document.querySelector('#login-password');const visible=input.type==='password';input.type=visible?'text':'password';el.textContent=visible?'Ocultar':'Mostrar';el.setAttribute('aria-pressed',String(visible));return;}
if(!authService.isAuthenticated())return;
if(el.hasAttribute('data-retry')){await boot();return;}
if(el.hasAttribute('data-logout')){try{authService.logout();resetData();ready=false;clearTimeout(timer);document.querySelector('#toast').classList.remove('visible');goHome();}catch(err){toast(err.message);}return;}
if(el.hasAttribute('data-close'))dialog.close();
if(el.dataset.route)location.hash=el.dataset.route;
if(el.hasAttribute('data-recharge'))modal('<span class="eyebrow">TU SIGUIENTE VIAJE</span><h2>Recargar saldo</h2><p>Recarga simulada. No se realizará ningún cobro.</p><form id="recharge-form"><label>Monto en soles<input name="amount" type="number" inputmode="decimal" min="10" max="2000" step="0.01" value="50" required></label><p class="form-error" role="alert"></p><button class="primary">Confirmar recarga</button></form>');
if(el.dataset.tab){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===el)));document.querySelector('#movements').innerHTML=movements(el.dataset.tab);}
if(el.dataset.detail){const t=transactionService.list().find(t=>t.id===el.dataset.detail);modal(`<span class="eyebrow">DETALLE DE MOVIMIENTO</span><h2>${money(t.amount)}</h2><p>${e(t.station)}</p><dl><dt>Fecha</dt><dd>${new Date(t.date).toLocaleString('es-PE')}</dd><dt>Vehículo</dt><dd>${e(t.vehicle)}</dd><dt>Puntos obtenidos</dt><dd>${t.points}</dd><dt>Referencia</dt><dd>${e(t.id)}</dd></dl><p class="fine-print">${t.type==='recarga'?'Recarga simulada local':'Consumo registrado · Primax Prime'}</p>`);}
if(el.dataset.benefit){const b=benefitsService.list().find(b=>b.id===el.dataset.benefit);modal(`<span class="eyebrow">BENEFICIO PRIME</span><h2>${e(b.title)}</h2><p>${e(b.description)}</p><p>Canje por <strong>${b.cost} puntos</strong>. El saldo se actualizará al confirmar.</p><p class="fine-print">Vigencia simulada: 31/12/2026. Sujeto a disponibilidad en estaciones participantes. Sin validez comercial.</p><p class="form-error" role="alert"></p><button class="primary" data-redeem="${b.id}">Canjear por ${b.cost} puntos</button>`);}
if(el.dataset.redeem){if(el.disabled)return;el.disabled=true;try{const coupon=await benefitsService.redeem(el.dataset.redeem);dialog.close();render();toast(`Canje listo. Código: ${coupon.id.slice(0,8).toUpperCase()}${coupon.refreshPending?' · Actualizaremos tu saldo al recuperar la conexión.':''}`);}catch(err){dialog.querySelector('.form-error').textContent=err.message;}finally{el.disabled=false;}}
if(el.id==='notifications')modal(`<h2>Notificaciones</h2><p>${settingsService.get().notifications?'¡Bienvenido a Prime! Descubre tus beneficios y disfruta cada parada.':'Las notificaciones de promociones están desactivadas en tus preferencias.'}</p><p class="fine-print">Mensajes simulados, sin conexión a un servicio push.</p>`);
if(el.hasAttribute('data-assistance'))modal('<h2>Asistencia Prime</h2><p>Este canal es una demostración local. No se enviará información a terceros.</p><form id="support-form"><label>¿En qué podemos ayudarte?<textarea name="message" maxlength="500" required rows="4"></textarea></label><button class="primary">Registrar consulta demo</button></form>');
});
document.addEventListener('change',event=>{if(!authService.isAuthenticated())return;if(event.target.id==='vehicle'){vehicleService.select(event.target.value);toast('Vehículo actualizado');}if(event.target.id==='notification-setting'){settingsService.notifications(event.target.checked);toast('Preferencia guardada');}});
document.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.target);try{if(event.target.id==='login-form'){const button=event.target.querySelector('[type="submit"]');if(button.disabled)return;button.disabled=true;try{await authService.login(data.get('email'),data.get('password'));await boot();}finally{button.disabled=false;}return;}if(!authService.isAuthenticated())return;if(event.target.id==='recharge-form'){transactionService.recharge(data.get('amount'));dialog.close();render();toast('Recarga simulada completada');}if(event.target.id==='profile-form'){memberService.setName(data.get('name'));render();toast('Preferencia de nombre guardada en este dispositivo');}if(event.target.id==='support-form'){dialog.close();toast('Consulta demo registrada. No se ha enviado.');}}catch(err){const error=event.target.querySelector('.form-error');if(error)error.textContent=err.message;else toast(err.message);}});
window.addEventListener('storage',event=>{if(event.key===SESSION_KEY||event.key===null){resetData();ready=false;void boot();}});
window.addEventListener('hashchange',render);
window.addEventListener('prime-session-expired',()=>{resetData();ready=false;render();});
window.addEventListener('focus',()=>void synchronize());
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void synchronize();});
setInterval(()=>{if(!document.hidden)void synchronize();},10000);
void boot();
