import test from 'node:test';import assert from 'node:assert/strict';import {refreshData,resetData,memberService,transactionService,benefitsService,vehicleService,settingsService,pointsService} from '../js/services/index.js';import {apiClient} from '../js/services/apiClient.js';import {SESSION_KEY} from '../js/services/session.js';
function setup(){resetData();const values=new Map([[SESSION_KEY,JSON.stringify({token:'jwt',expiresAt:Date.now()+60000,user:{id:'user'}})]]);globalThis.localStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});assert.equal(options.headers.Authorization,'Bearer jwt');let data;if(url==='/api/v1/memberships/me')data={user:{name:'Diego'},number:'PRIME-0001',points:100,status:'ACTIVE',vehicles:[{plate:'ABC-123',label:'Mi auto'},{plate:'DEF-456',label:'Familiar'}]};else if(url.includes('/transactions?'))data=[{id:'tx',amount:'100.00',pointsEarned:100,createdAt:'2026-10-09T00:00:00Z',vehicle:{plate:'ABC-123'},station:{name:'Primax Sur'},status:'PAID'}];else if(url.includes('/rewards?'))data=[{id:'reward',transactionId:'tx',points:100,kind:'EARN',createdAt:'2026-10-09T00:00:00Z'}];else if(url.includes('/redemptions?'))data=[];else if(url==='/api/v1/benefits')data=[{id:'coffee-id',code:'coffee',title:'Café',pointsCost:400}];else if(url==='/api/v1/rewards/redeem')data={redemption:{id:'coupon'}};else throw Error(url);return Response.json(data);};return {values,calls};}
test('carga membresía, vehículos, historial, puntos y beneficios reales de API',async()=>{setup();await refreshData();assert.equal(memberService.get().name,'Diego');assert.equal(memberService.get().number,'PRIME-0001');assert.equal(memberService.get().points,100);assert.equal(transactionService.list()[0].station,'Primax Sur');assert.equal(pointsService.list()[0].transactionId,'tx');assert.equal(benefitsService.list()[0].cost,400);assert.equal(vehicleService.selected(),'ABC-123');});
test('recarga demo no modifica puntos reales; valida importes',async()=>{setup();await refreshData();transactionService.recharge(50);assert.equal(memberService.get().balance,50);assert.equal(memberService.get().points,100);assert.equal(transactionService.totals().consumption,100);for(const v of [-1,0,9,2001,NaN,Infinity,10.001])assert.throws(()=>transactionService.recharge(v));});
test('canje llama API con UUID; la UI no inventa puntos ni cupones',async()=>{const {calls}=setup();await refreshData();const coupon=await benefitsService.redeem('coffee-id');assert.equal(coupon.id,'coupon');const request=calls.find(c=>c.url==='/api/v1/rewards/redeem');assert.equal(JSON.parse(request.options.body).benefitId,'coffee-id');assert.match(JSON.parse(request.options.body).operationId,/^[a-f0-9-]{36}$/);});
test('vehículos, nombre local y preferencias conservan usuario real',async()=>{setup();await refreshData();vehicleService.select('DEF-456');assert.throws(()=>vehicleService.select('invalid'));settingsService.notifications(false);memberService.setName('Andrea');assert.equal(memberService.get().name,'Diego');assert.equal(memberService.get().alias,'Andrea');assert.throws(()=>memberService.setName(' '));assert.throws(()=>memberService.setName('a'.repeat(81)));assert.equal(settingsService.get().notifications,false);});
test('error 503 conserva últimos datos y 401 elimina sesión',async()=>{const {values}=setup();await refreshData();globalThis.fetch=async()=>Response.json({message:'internal details'},{status:503});await assert.rejects(refreshData(),/no está disponible/);assert.equal(memberService.get().points,100);globalThis.fetch=async()=>Response.json({},{status:401});await assert.rejects(apiClient('/memberships/me'),/sesión venció/);assert.equal(values.has(SESSION_KEY),false);});

test('historial pagina sin perder registros después de cien consumos',async()=>{
 setup();let pages=[];globalThis.fetch=async url=>{const p=new URL(url,'http://test').searchParams.get('page');pages.push(p);return Response.json(Array.from({length:p==='1'?100:1},(_,i)=>({id:p+'-'+i})));};
 const {transactionsService}=await import('../js/services/transactionsService.js');const rows=await transactionsService.list();assert.equal(rows.length,101);assert.deepEqual(pages,['1','2']);
});
test('canje confirmado no se vuelve error si falla actualizar el saldo',async()=>{
 setup();await refreshData();globalThis.fetch=async(url)=>url.endsWith('/rewards/redeem')?Response.json({redemption:{id:'confirmed-coupon'}},{status:201}):Response.json({},{status:503});
 const result=await benefitsService.redeem('coffee-id');assert.equal(result.id,'confirmed-coupon');assert.equal(result.refreshPending,true);
});
